import { SKILL_NAMES } from "./constants.js"

export const SKILL_INFO = {
  [SKILL_NAMES.LAYOUT]: {
    label: "Верстка",
  },
  [SKILL_NAMES.WORKPRESS]: {
    label: "Workpress",
  },
  [SKILL_NAMES.FREELANCE]: {
    label: "Фриланс",
  },
}

export const ORDER_TEMPLATES = [
  {
    title: "Простой лендинг",
    skill: SKILL_NAMES.LAYOUT,
    description: "Одностраничный сайт с базовой версткой",
    baseReward: 3000,
    reputation: 1,
    energyCost: 25,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Визитка для фотографа",
    skill: SKILL_NAMES.LAYOUT,
    description: "Минималистичный сайт-портфолио с галереей",
    baseReward: 4000,
    reputation: 1,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Лендинг по недвижимости",
    skill: SKILL_NAMES.LAYOUT,
    description: "Посадочная страница с адаптивом",
    baseReward: 12000,
    reputation: 1,
    energyCost: 35,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Корпоративный сайт",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт компании с формами",
    baseReward: 15000,
    reputation: 2,
    energyCost: 40,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Интерактивный лендинг",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сайт с параллакс-эффектами и анимациями",
    baseReward: 18000,
    reputation: 2,
    energyCost: 42,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сложный лендинг с анимациями",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт с анимациями",
    baseReward: 13000,
    reputation: 2,
    energyCost: 45,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Простой сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Базовая установка Workpress с готовой темой",
    baseReward: 5000,
    reputation: 1,
    energyCost: 30,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Блог на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настроить блог с категориями и комментариями",
    baseReward: 6000,
    reputation: 1,
    energyCost: 32,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Типовой сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Сверстать тему и натянуть на Workpress",
    baseReward: 14000,
    reputation: 2,
    energyCost: 45,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сайт с кастомными полями",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настроить ACF и создать удобные шаблоны",
    baseReward: 16000,
    reputation: 2,
    energyCost: 48,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Интернет-магазин Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Полноценный магазин с кастомными полями",
    baseReward: 20000,
    reputation: 3,
    energyCost: 60,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Консультация клиента",
    skill: SKILL_NAMES.FREELANCE,
    description: "Помочь определиться с требованиями к проекту",
    baseReward: 2000,
    reputation: 1,
    energyCost: 15,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Аудит сайта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проверить сайт на ошибки и дать рекомендации",
    baseReward: 3000,
    reputation: 1,
    energyCost: 20,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Правки для постоянного заказчика",
    skill: SKILL_NAMES.FREELANCE,
    description: "Исправить адаптив и настроить метрики",
    baseReward: 5000,
    reputation: 1,
    energyCost: 25,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Техническое задание",
    skill: SKILL_NAMES.FREELANCE,
    description: "Составить подробное ТЗ для разработчиков",
    baseReward: 8000,
    reputation: 2,
    energyCost: 30,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Ведение проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Полное сопровождение проекта от ТЗ до сдачи",
    baseReward: 25000,
    reputation: 3,
    energyCost: 50,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Адаптивная верстка",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сверстать макет с адаптивом под все устройства",
    baseReward: 8000,
    reputation: 1,
    energyCost: 32,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Верстка email-рассылки",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сверстать письмо для email-маркетинга",
    baseReward: 4500,
    reputation: 1,
    energyCost: 25,
    timeRequired: 2,
    requiredLevel: 2,
  },
  {
    title: "Портфолио дизайнера",
    skill: SKILL_NAMES.LAYOUT,
    description: "Креативный сайт-портфолио с галереей работ",
    baseReward: 20000,
    reputation: 2,
    energyCost: 48,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Интернет-магазин",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный магазин с каталогом и корзиной",
    baseReward: 30000,
    reputation: 3,
    energyCost: 55,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Настройка плагинов Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Установить и настроить нужные плагины",
    baseReward: 7000,
    reputation: 1,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Оптимизация Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Ускорить загрузку сайта и настроить кеширование",
    baseReward: 10000,
    reputation: 2,
    energyCost: 38,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Миграция на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Перенести сайт с другой CMS на Workpress",
    baseReward: 18000,
    reputation: 2,
    energyCost: 52,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Кастомная тема Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Разработать уникальную тему с нуля",
    baseReward: 35000,
    reputation: 3,
    energyCost: 65,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Переговоры с заказчиком",
    skill: SKILL_NAMES.FREELANCE,
    description: "Провести встречу и согласовать детали проекта",
    baseReward: 3500,
    reputation: 1,
    energyCost: 18,
    timeRequired: 2,
    requiredLevel: 2,
  },
  {
    title: "Презентация проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Подготовить и провести презентацию для клиента",
    baseReward: 6000,
    reputation: 2,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 3,
  },
  {
    title: "Управление командой",
    skill: SKILL_NAMES.FREELANCE,
    description: "Координировать работу дизайнера и разработчика",
    baseReward: 15000,
    reputation: 2,
    energyCost: 42,
    timeRequired: 5,
    requiredLevel: 4,
  },
  {
    title: "Крупный проект под ключ",
    skill: SKILL_NAMES.FREELANCE,
    description: "Полный цикл разработки корпоративного сайта",
    baseReward: 40000,
    reputation: 4,
    energyCost: 60,
    timeRequired: 10,
    requiredLevel: 5,
  },
  {
    title: "Сайт-визитка для ресторана",
    skill: SKILL_NAMES.LAYOUT,
    description: "Простая визитка с меню и контактами",
    baseReward: 3500,
    reputation: 1,
    energyCost: 26,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Лендинг для салона красоты",
    skill: SKILL_NAMES.LAYOUT,
    description: "Одностраничный сайт с галереей услуг",
    baseReward: 4500,
    reputation: 1,
    energyCost: 27,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Сайт для стоматологии",
    skill: SKILL_NAMES.LAYOUT,
    description: "Информационный сайт с записью онлайн",
    baseReward: 5000,
    reputation: 1,
    energyCost: 29,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Лендинг для автосервиса",
    skill: SKILL_NAMES.LAYOUT,
    description: "Посадочная страница с прайс-листом",
    baseReward: 5500,
    reputation: 1,
    energyCost: 30,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Сайт для фитнес-клуба",
    skill: SKILL_NAMES.LAYOUT,
    description: "Лендинг с расписанием и ценами",
    baseReward: 6000,
    reputation: 1,
    energyCost: 31,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Адаптивная верстка лендинга",
    skill: SKILL_NAMES.LAYOUT,
    description: "Лендинг с полной адаптивностью для мобильных",
    baseReward: 9000,
    reputation: 1,
    energyCost: 33,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Сайт для строительной компании",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт с портфолио проектов",
    baseReward: 10000,
    reputation: 1,
    energyCost: 34,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Лендинг для онлайн-школы",
    skill: SKILL_NAMES.LAYOUT,
    description: "Посадочная страница с формой регистрации",
    baseReward: 11000,
    reputation: 1,
    energyCost: 36,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Верстка промо-страницы",
    skill: SKILL_NAMES.LAYOUT,
    description: "Промо-лендинг для запуска продукта",
    baseReward: 13000,
    reputation: 1,
    energyCost: 37,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Сайт для юридической фирмы",
    skill: SKILL_NAMES.LAYOUT,
    description: "Корпоративный сайт с формой обратной связи",
    baseReward: 14000,
    reputation: 1,
    energyCost: 38,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Многостраничный сайт агентства",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сайт с услугами, портфолио и командой",
    baseReward: 16000,
    reputation: 2,
    energyCost: 41,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Лендинг с видео-фоном",
    skill: SKILL_NAMES.LAYOUT,
    description: "Современный лендинг с фоновым видео",
    baseReward: 17000,
    reputation: 2,
    energyCost: 43,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сайт для медицинской клиники",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт с онлайн-записью",
    baseReward: 19000,
    reputation: 2,
    energyCost: 44,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Портфолио архитектора",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сайт-портфолио с 3D галереей проектов",
    baseReward: 21000,
    reputation: 2,
    energyCost: 46,
    timeRequired: 6,
    requiredLevel: 3,
  },
  {
    title: "Сайт для IT-компании",
    skill: SKILL_NAMES.LAYOUT,
    description: "Корпоративный сайт с анимациями",
    baseReward: 22000,
    reputation: 2,
    energyCost: 47,
    timeRequired: 6,
    requiredLevel: 3,
  },
  {
    title: "Интерактивный сайт-портфолио",
    skill: SKILL_NAMES.LAYOUT,
    description: "Креативное портфолио с интерактивными элементами",
    baseReward: 23000,
    reputation: 2,
    energyCost: 49,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Лендинг для продажи курса",
    skill: SKILL_NAMES.LAYOUT,
    description: "Высококонверсионный лендинг с оплатой",
    baseReward: 24000,
    reputation: 2,
    energyCost: 50,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Сайт для турагентства",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт с каталогом туров",
    baseReward: 25000,
    reputation: 2,
    energyCost: 51,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Веб-приложение с дашбордом",
    skill: SKILL_NAMES.LAYOUT,
    description: "Интерфейс админ-панели с графиками",
    baseReward: 26000,
    reputation: 2,
    energyCost: 52,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Сайт для рекламного агентства",
    skill: SKILL_NAMES.LAYOUT,
    description: "Креативный сайт с интерактивными кейсами",
    baseReward: 27000,
    reputation: 2,
    energyCost: 53,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Корпоративный портал",
    skill: SKILL_NAMES.LAYOUT,
    description: "Внутренний портал для сотрудников",
    baseReward: 28000,
    reputation: 3,
    energyCost: 54,
    timeRequired: 7,
    requiredLevel: 5,
  },
  {
    title: "E-commerce платформа",
    skill: SKILL_NAMES.LAYOUT,
    description: "Полноценный интернет-магазин с личным кабинетом",
    baseReward: 32000,
    reputation: 3,
    energyCost: 56,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Сайт для образовательной платформы",
    skill: SKILL_NAMES.LAYOUT,
    description: "Платформа для онлайн-обучения с видеоплеером",
    baseReward: 34000,
    reputation: 3,
    energyCost: 57,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Маркетплейс",
    skill: SKILL_NAMES.LAYOUT,
    description: "Площадка для торговли с личными кабинетами",
    baseReward: 36000,
    reputation: 3,
    energyCost: 58,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Крупный корпоративный сайт",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многофункциональный сайт для крупной компании",
    baseReward: 38000,
    reputation: 3,
    energyCost: 59,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Сложное веб-приложение",
    skill: SKILL_NAMES.LAYOUT,
    description: "SPA приложение с множеством функций",
    baseReward: 42000,
    reputation: 4,
    energyCost: 62,
    timeRequired: 10,
    requiredLevel: 6,
  },
  {
    title: "Профессиональный лендинг",
    skill: SKILL_NAMES.LAYOUT,
    description: "Премиум лендинг с уникальным дизайном",
    baseReward: 44000,
    reputation: 4,
    energyCost: 63,
    timeRequired: 10,
    requiredLevel: 6,
  },
  {
    title: "Платформа для фрилансеров",
    skill: SKILL_NAMES.LAYOUT,
    description: "Биржа фриланса с системой отзывов",
    baseReward: 46000,
    reputation: 4,
    energyCost: 64,
    timeRequired: 10,
    requiredLevel: 6,
  },
  {
    title: "Система управления проектами",
    skill: SKILL_NAMES.LAYOUT,
    description: "Комплексная система для управления задачами",
    baseReward: 48000,
    reputation: 4,
    energyCost: 65,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Интерфейс аналитической платформы",
    skill: SKILL_NAMES.LAYOUT,
    description: "Дашборд с визуализацией данных",
    baseReward: 50000,
    reputation: 4,
    energyCost: 66,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Корпоративный портал уровня Enterprise",
    skill: SKILL_NAMES.LAYOUT,
    description: "Масштабируемый портал для крупной корпорации",
    baseReward: 52000,
    reputation: 4,
    energyCost: 67,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Высоконагруженная платформа",
    skill: SKILL_NAMES.LAYOUT,
    description: "Платформа с оптимизацией под большие нагрузки",
    baseReward: 55000,
    reputation: 5,
    energyCost: 70,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Сложная CRM система",
    skill: SKILL_NAMES.LAYOUT,
    description: "Полнофункциональная CRM с аналитикой",
    baseReward: 58000,
    reputation: 5,
    energyCost: 72,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Маркетплейс B2B",
    skill: SKILL_NAMES.LAYOUT,
    description: "Бизнес-платформа для оптовой торговли",
    baseReward: 60000,
    reputation: 5,
    energyCost: 73,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Платформа для онлайн-конференций",
    skill: SKILL_NAMES.LAYOUT,
    description: "Комплексная система для видеоконференций",
    baseReward: 62000,
    reputation: 5,
    energyCost: 74,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Система электронного документооборота",
    skill: SKILL_NAMES.LAYOUT,
    description: "Платформа для управления документами",
    baseReward: 64000,
    reputation: 5,
    energyCost: 75,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Enterprise веб-приложение",
    skill: SKILL_NAMES.LAYOUT,
    description: "Корпоративное решение корпоративного уровня",
    baseReward: 66000,
    reputation: 5,
    energyCost: 76,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Мега-проект корпоративного сайта",
    skill: SKILL_NAMES.LAYOUT,
    description: "Масштабный сайт международной компании",
    baseReward: 70000,
    reputation: 6,
    energyCost: 80,
    timeRequired: 14,
    requiredLevel: 8,
  },
  {
    title: "Платформа для финтех-стартапа",
    skill: SKILL_NAMES.LAYOUT,
    description: "Банковская платформа с высоким уровнем безопасности",
    baseReward: 75000,
    reputation: 6,
    energyCost: 82,
    timeRequired: 14,
    requiredLevel: 8,
  },
  {
    title: "Глобальная e-commerce платформа",
    skill: SKILL_NAMES.LAYOUT,
    description: "Международный маркетплейс с мультиязычностью",
    baseReward: 80000,
    reputation: 6,
    energyCost: 84,
    timeRequired: 15,
    requiredLevel: 8,
  },
  {
    title: "Образовательная экосистема",
    skill: SKILL_NAMES.LAYOUT,
    description: "Комплексная платформа для онлайн-университета",
    baseReward: 85000,
    reputation: 6,
    energyCost: 86,
    timeRequired: 15,
    requiredLevel: 8,
  },
  {
    title: "Корпоративная экосистема",
    skill: SKILL_NAMES.LAYOUT,
    description: "Интегрированная система для крупного холдинга",
    baseReward: 90000,
    reputation: 6,
    energyCost: 88,
    timeRequired: 15,
    requiredLevel: 8,
  },
  {
    title: "Премиум веб-решение",
    skill: SKILL_NAMES.LAYOUT,
    description: "Уникальное решение мирового уровня",
    baseReward: 95000,
    reputation: 6,
    energyCost: 90,
    timeRequired: 16,
    requiredLevel: 8,
  },
  {
    title: "Легендарный корпоративный портал",
    skill: SKILL_NAMES.LAYOUT,
    description: "Максимально сложный проект корпоративного уровня",
    baseReward: 100000,
    reputation: 7,
    energyCost: 95,
    timeRequired: 16,
    requiredLevel: 9,
  },
  {
    title: "Платформа нового поколения",
    skill: SKILL_NAMES.LAYOUT,
    description: "Инновационная платформа с AI-интеграцией",
    baseReward: 110000,
    reputation: 7,
    energyCost: 98,
    timeRequired: 17,
    requiredLevel: 9,
  },
  {
    title: "Глобальная корпоративная система",
    skill: SKILL_NAMES.LAYOUT,
    description: "Система для транснациональной корпорации",
    baseReward: 120000,
    reputation: 7,
    energyCost: 100,
    timeRequired: 17,
    requiredLevel: 9,
  },
  {
    title: "Мега-платформа для бизнеса",
    skill: SKILL_NAMES.LAYOUT,
    description: "Комплексное решение уровня Fortune 500",
    baseReward: 130000,
    reputation: 7,
    energyCost: 102,
    timeRequired: 18,
    requiredLevel: 9,
  },
  {
    title: "Экосистема мирового уровня",
    skill: SKILL_NAMES.LAYOUT,
    description: "Интегрированная платформа международного масштаба",
    baseReward: 140000,
    reputation: 7,
    energyCost: 105,
    timeRequired: 18,
    requiredLevel: 9,
  },
  {
    title: "Проект года в веб-разработке",
    skill: SKILL_NAMES.LAYOUT,
    description: "Революционное веб-решение премиум класса",
    baseReward: 150000,
    reputation: 7,
    energyCost: 108,
    timeRequired: 19,
    requiredLevel: 9,
  },
  {
    title: "Вершина мастерства веб-разработки",
    skill: SKILL_NAMES.LAYOUT,
    description: "Абсолютный шедевр веб-разработки",
    baseReward: 180000,
    reputation: 8,
    energyCost: 115,
    timeRequired: 20,
    requiredLevel: 10,
  },
  {
    title: "Легендарный проект веб-индустрии",
    skill: SKILL_NAMES.LAYOUT,
    description: "Проект, который войдет в историю веб-разработки",
    baseReward: 200000,
    reputation: 8,
    energyCost: 120,
    timeRequired: 20,
    requiredLevel: 10,
  },
  {
    title: "Платформа будущего",
    skill: SKILL_NAMES.LAYOUT,
    description: "Инновационная платформа следующего поколения",
    baseReward: 220000,
    reputation: 8,
    energyCost: 125,
    timeRequired: 21,
    requiredLevel: 10,
  },
  {
    title: "Корпоративная экосистема уровня ТОП-100",
    skill: SKILL_NAMES.LAYOUT,
    description: "Система для одной из крупнейших корпораций мира",
    baseReward: 250000,
    reputation: 8,
    energyCost: 130,
    timeRequired: 21,
    requiredLevel: 10,
  },
  {
    title: "Проект уровня технического директора",
    skill: SKILL_NAMES.LAYOUT,
    description:
      "Решение, созданное для технического директора крупной компании",
    baseReward: 280000,
    reputation: 8,
    energyCost: 135,
    timeRequired: 22,
    requiredLevel: 10,
  },
  {
    title: "Абсолютный пик веб-разработки",
    skill: SKILL_NAMES.LAYOUT,
    description: "Проект, который определяет будущее веб-разработки",
    baseReward: 300000,
    reputation: 9,
    energyCost: 140,
    timeRequired: 22,
    requiredLevel: 10,
  },
  {
    title: "Базовая настройка Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Установка Workpress и базовая настройка",
    baseReward: 4500,
    reputation: 1,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Простой блог на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настройка блога с базовыми плагинами",
    baseReward: 5500,
    reputation: 1,
    energyCost: 29,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Сайт-визитка на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Простой сайт на готовой теме Workpress",
    baseReward: 6500,
    reputation: 1,
    energyCost: 31,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Лендинг на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Одностраничный сайт на Workpress",
    baseReward: 7500,
    reputation: 1,
    energyCost: 33,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Портфолио на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Сайт-портфолио на Workpress теме",
    baseReward: 8500,
    reputation: 1,
    energyCost: 35,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Настройка SEO для Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Оптимизация сайта для поисковых систем",
    baseReward: 8000,
    reputation: 1,
    energyCost: 30,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Многостраничный сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Сайт с несколькими страницами и меню",
    baseReward: 11000,
    reputation: 1,
    energyCost: 36,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Сайт с формой обратной связи",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настройка форм и интеграция с почтой",
    baseReward: 12000,
    reputation: 1,
    energyCost: 37,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Сайт с галереей на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Портфолио с галереей изображений",
    baseReward: 13000,
    reputation: 1,
    energyCost: 39,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Блог с категориями",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Расширенный блог с системой категорий",
    baseReward: 15000,
    reputation: 2,
    energyCost: 40,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Сайт с мультиязычностью",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Многоязычный сайт на Workpress",
    baseReward: 17000,
    reputation: 2,
    energyCost: 42,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Корпоративный сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Профессиональный корпоративный сайт",
    baseReward: 19000,
    reputation: 2,
    energyCost: 44,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сайт с кастомными типами постов",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настройка CPT и таксономий",
    baseReward: 20000,
    reputation: 2,
    energyCost: 46,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Workpress с интеграцией API",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Подключение внешних сервисов через API",
    baseReward: 21000,
    reputation: 2,
    energyCost: 47,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Продвинутый интернет-магазин",
    skill: SKILL_NAMES.WORKPRESS,
    description: "WooCommerce магазин с расширенным функционалом",
    baseReward: 22000,
    reputation: 2,
    energyCost: 48,
    timeRequired: 6,
    requiredLevel: 3,
  },
  {
    title: "Сайт с системой бронирования",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Платформа для онлайн-бронирования",
    baseReward: 24000,
    reputation: 2,
    energyCost: 50,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Workpress с личным кабинетом",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Сайт с регистрацией и личными кабинетами",
    baseReward: 26000,
    reputation: 2,
    energyCost: 51,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Сложная тема Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Разработка кастомной темы с нуля",
    baseReward: 28000,
    reputation: 2,
    energyCost: 53,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Workpress с подписками",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Система платных подписок на контент",
    baseReward: 30000,
    reputation: 2,
    energyCost: 54,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Многосайтовая сеть Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настройка мультисайта Workpress",
    baseReward: 32000,
    reputation: 3,
    energyCost: 55,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Крупный интернет-магазин",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Магазин с тысячами товаров и фильтрами",
    baseReward: 36000,
    reputation: 3,
    energyCost: 57,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Workpress для новостного портала",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Портал с системой модерации контента",
    baseReward: 38000,
    reputation: 3,
    energyCost: 58,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Платформа для онлайн-курсов",
    skill: SKILL_NAMES.WORKPRESS,
    description: "LMS система на базе Workpress",
    baseReward: 40000,
    reputation: 3,
    energyCost: 59,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Workpress с кастомным админ-интерфейсом",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Полностью переработанная админка",
    baseReward: 42000,
    reputation: 3,
    energyCost: 61,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Enterprise Workpress решение",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Корпоративное решение на Workpress",
    baseReward: 45000,
    reputation: 3,
    energyCost: 62,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Сложная Workpress экосистема",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Многофункциональная платформа на Workpress",
    baseReward: 48000,
    reputation: 4,
    energyCost: 64,
    timeRequired: 9,
    requiredLevel: 6,
  },
  {
    title: "Workpress с микросервисами",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Интеграция Workpress с микросервисной архитектурой",
    baseReward: 50000,
    reputation: 4,
    energyCost: 66,
    timeRequired: 10,
    requiredLevel: 6,
  },
  {
    title: "Маркетплейс на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Многопродавцовый маркетплейс на Workpress",
    baseReward: 52000,
    reputation: 4,
    energyCost: 68,
    timeRequired: 10,
    requiredLevel: 6,
  },
  {
    title: "Workpress для медиа-холдинга",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Медиа-платформа с высокой нагрузкой",
    baseReward: 54000,
    reputation: 4,
    energyCost: 70,
    timeRequired: 10,
    requiredLevel: 6,
  },
  {
    title: "Корпоративный портал Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Портал для крупной корпорации на Workpress",
    baseReward: 56000,
    reputation: 4,
    energyCost: 71,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Workpress экосистема Enterprise",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Комплексное решение корпоративного уровня",
    baseReward: 58000,
    reputation: 4,
    energyCost: 72,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Высоконагруженная Workpress платформа",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Оптимизация под миллионы пользователей",
    baseReward: 62000,
    reputation: 5,
    energyCost: 75,
    timeRequired: 11,
    requiredLevel: 7,
  },
  {
    title: "Workpress для финтех-проекта",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Безопасная платформа для финансовых операций",
    baseReward: 65000,
    reputation: 5,
    energyCost: 77,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Глобальная Workpress сеть",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Международная мультисайтовая сеть",
    baseReward: 68000,
    reputation: 5,
    energyCost: 78,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Workpress CRM интеграция",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Интеграция Workpress с корпоративной CRM",
    baseReward: 70000,
    reputation: 5,
    energyCost: 80,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Enterprise Workpress экосистема",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Полноценная экосистема для крупного бизнеса",
    baseReward: 72000,
    reputation: 5,
    energyCost: 81,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Workpress платформа нового уровня",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Инновационная платформа на базе Workpress",
    baseReward: 75000,
    reputation: 5,
    energyCost: 83,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Мега-проект Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Крупнейший проект на Workpress",
    baseReward: 80000,
    reputation: 6,
    energyCost: 85,
    timeRequired: 14,
    requiredLevel: 8,
  },
  {
    title: "Workpress экосистема мирового уровня",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Глобальная платформа на Workpress",
    baseReward: 85000,
    reputation: 6,
    energyCost: 87,
    timeRequired: 14,
    requiredLevel: 8,
  },
  {
    title: "Корпоративный Workpress портал",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Портал для международной корпорации",
    baseReward: 90000,
    reputation: 6,
    energyCost: 89,
    timeRequired: 15,
    requiredLevel: 8,
  },
  {
    title: "Workpress решение Fortune 500",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Решение для одной из крупнейших компаний",
    baseReward: 95000,
    reputation: 6,
    energyCost: 91,
    timeRequired: 15,
    requiredLevel: 8,
  },
  {
    title: "Премиум Workpress платформа",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Уникальное решение премиум класса",
    baseReward: 100000,
    reputation: 6,
    energyCost: 93,
    timeRequired: 16,
    requiredLevel: 8,
  },
  {
    title: "Легендарная Workpress платформа",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Проект, определяющий будущее Workpress",
    baseReward: 110000,
    reputation: 7,
    energyCost: 96,
    timeRequired: 16,
    requiredLevel: 9,
  },
  {
    title: "Workpress экосистема нового поколения",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Инновационная экосистема с AI",
    baseReward: 120000,
    reputation: 7,
    energyCost: 98,
    timeRequired: 17,
    requiredLevel: 9,
  },
  {
    title: "Глобальная Workpress сеть",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Международная сеть мирового масштаба",
    baseReward: 130000,
    reputation: 7,
    energyCost: 100,
    timeRequired: 17,
    requiredLevel: 9,
  },
  {
    title: "Workpress платформа уровня CTO",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Решение для технического директора",
    baseReward: 140000,
    reputation: 7,
    energyCost: 102,
    timeRequired: 18,
    requiredLevel: 9,
  },
  {
    title: "Enterprise Workpress мега-система",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Комплексная система для крупного холдинга",
    baseReward: 150000,
    reputation: 7,
    energyCost: 104,
    timeRequired: 18,
    requiredLevel: 9,
  },
  {
    title: "Проект года Workpress индустрии",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Революционное решение премиум класса",
    baseReward: 160000,
    reputation: 7,
    energyCost: 106,
    timeRequired: 19,
    requiredLevel: 9,
  },
  {
    title: "Абсолютный пик Workpress разработки",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Вершина мастерства в Workpress",
    baseReward: 180000,
    reputation: 8,
    energyCost: 110,
    timeRequired: 20,
    requiredLevel: 10,
  },
  {
    title: "Легенда Workpress разработки",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Проект, который войдет в историю Workpress",
    baseReward: 200000,
    reputation: 8,
    energyCost: 115,
    timeRequired: 20,
    requiredLevel: 10,
  },
  {
    title: "Workpress платформа будущего",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Инновационная платформа следующего поколения",
    baseReward: 220000,
    reputation: 8,
    energyCost: 120,
    timeRequired: 21,
    requiredLevel: 10,
  },
  {
    title: "Workpress экосистема ТОП-100",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Система для одной из крупнейших корпораций",
    baseReward: 250000,
    reputation: 8,
    energyCost: 125,
    timeRequired: 21,
    requiredLevel: 10,
  },
  {
    title: "Workpress решение уровня технического директора",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Решение для CTO крупной компании",
    baseReward: 280000,
    reputation: 8,
    energyCost: 130,
    timeRequired: 22,
    requiredLevel: 10,
  },
  {
    title: "Абсолютный шедевр Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Проект, определяющий будущее Workpress разработки",
    baseReward: 300000,
    reputation: 9,
    energyCost: 135,
    timeRequired: 22,
    requiredLevel: 10,
  },
  {
    title: "Первичная консультация по проекту",
    skill: SKILL_NAMES.FREELANCE,
    description: "Консультация перед началом работы",
    baseReward: 1500,
    reputation: 1,
    energyCost: 12,
    timeRequired: 1,
    requiredLevel: 1,
  },
  {
    title: "Оценка стоимости проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Подготовка коммерческого предложения",
    baseReward: 2500,
    reputation: 1,
    energyCost: 14,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Устранение критических ошибок",
    skill: SKILL_NAMES.FREELANCE,
    description: "Срочное исправление багов на сайте",
    baseReward: 3500,
    reputation: 1,
    energyCost: 16,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Консультация по оптимизации",
    skill: SKILL_NAMES.FREELANCE,
    description: "Рекомендации по улучшению сайта",
    baseReward: 4000,
    reputation: 1,
    energyCost: 17,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Разбор кейса клиента",
    skill: SKILL_NAMES.FREELANCE,
    description: "Анализ проекта и рекомендации",
    baseReward: 4500,
    reputation: 1,
    energyCost: 19,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Техническая поддержка сайта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Ежемесячная поддержка и обновления",
    baseReward: 5500,
    reputation: 1,
    energyCost: 22,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Согласование дизайн-макетов",
    skill: SKILL_NAMES.FREELANCE,
    description: "Работа с дизайнером и клиентом",
    baseReward: 6000,
    reputation: 1,
    energyCost: 23,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Оптимизация производительности",
    skill: SKILL_NAMES.FREELANCE,
    description: "Ускорение загрузки и оптимизация кода",
    baseReward: 7000,
    reputation: 1,
    energyCost: 24,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Интеграция платежных систем",
    skill: SKILL_NAMES.FREELANCE,
    description: "Подключение способов оплаты",
    baseReward: 7500,
    reputation: 1,
    energyCost: 26,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Настройка аналитики",
    skill: SKILL_NAMES.FREELANCE,
    description: "Установка и настройка систем аналитики",
    baseReward: 8500,
    reputation: 1,
    energyCost: 27,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Ведение переговоров с заказчиком",
    skill: SKILL_NAMES.FREELANCE,
    description: "Профессиональные переговоры и согласования",
    baseReward: 9000,
    reputation: 2,
    energyCost: 29,
    timeRequired: 3,
    requiredLevel: 3,
  },
  {
    title: "Управление разработкой",
    skill: SKILL_NAMES.FREELANCE,
    description: "Координация работы команды разработчиков",
    baseReward: 10000,
    reputation: 2,
    energyCost: 31,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Составление детального ТЗ",
    skill: SKILL_NAMES.FREELANCE,
    description: "Подробное техническое задание проекта",
    baseReward: 11000,
    reputation: 2,
    energyCost: 32,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Презентация проекта заказчику",
    skill: SKILL_NAMES.FREELANCE,
    description: "Подготовка и проведение презентации",
    baseReward: 12000,
    reputation: 2,
    energyCost: 33,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Управление изменениями ТЗ",
    skill: SKILL_NAMES.FREELANCE,
    description: "Обработка изменений в требованиях",
    baseReward: 13000,
    reputation: 2,
    energyCost: 34,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Полное сопровождение проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "End-to-end управление проектом",
    baseReward: 28000,
    reputation: 2,
    energyCost: 51,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Координация команды разработки",
    skill: SKILL_NAMES.FREELANCE,
    description: "Управление командой из 3-5 человек",
    baseReward: 30000,
    reputation: 2,
    energyCost: 52,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Управление большим проектом",
    skill: SKILL_NAMES.FREELANCE,
    description: "Руководство крупным проектом",
    baseReward: 32000,
    reputation: 2,
    energyCost: 53,
    timeRequired: 8,
    requiredLevel: 4,
  },
  {
    title: "Переговоры с крупным заказчиком",
    skill: SKILL_NAMES.FREELANCE,
    description: "Работа с ключевыми клиентами",
    baseReward: 34000,
    reputation: 2,
    energyCost: 54,
    timeRequired: 8,
    requiredLevel: 4,
  },
  {
    title: "Управление несколькими проектами",
    skill: SKILL_NAMES.FREELANCE,
    description: "Параллельное ведение нескольких проектов",
    baseReward: 38000,
    reputation: 3,
    energyCost: 55,
    timeRequired: 8,
    requiredLevel: 4,
  },
  {
    title: "Ведущий менеджер проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Руководство стратегическим проектом",
    baseReward: 42000,
    reputation: 3,
    energyCost: 57,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Управление корпоративным проектом",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проект для крупной корпорации",
    baseReward: 45000,
    reputation: 3,
    energyCost: 58,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Переговоры на уровне директоров",
    skill: SKILL_NAMES.FREELANCE,
    description: "Работа с топ-менеджментом компании",
    baseReward: 48000,
    reputation: 3,
    energyCost: 59,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Управление международным проектом",
    skill: SKILL_NAMES.FREELANCE,
    description: "Координация проекта с зарубежными клиентами",
    baseReward: 50000,
    reputation: 3,
    energyCost: 61,
    timeRequired: 10,
    requiredLevel: 5,
  },
  {
    title: "Стратегическое планирование проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Долгосрочное планирование и развитие",
    baseReward: 52000,
    reputation: 3,
    energyCost: 62,
    timeRequired: 10,
    requiredLevel: 5,
  },
  {
    title: "Управление программой проектов",
    skill: SKILL_NAMES.FREELANCE,
    description: "Координация программы из нескольких проектов",
    baseReward: 55000,
    reputation: 4,
    energyCost: 64,
    timeRequired: 10,
    requiredLevel: 6,
  },
  {
    title: "Руководство отделом разработки",
    skill: SKILL_NAMES.FREELANCE,
    description: "Управление командой разработки",
    baseReward: 58000,
    reputation: 4,
    energyCost: 66,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Управление трансформацией компании",
    skill: SKILL_NAMES.FREELANCE,
    description: "Цифровая трансформация бизнеса",
    baseReward: 60000,
    reputation: 4,
    energyCost: 68,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Переговоры на C-level",
    skill: SKILL_NAMES.FREELANCE,
    description: "Работа с CEO и CTO компаний",
    baseReward: 62000,
    reputation: 4,
    energyCost: 70,
    timeRequired: 11,
    requiredLevel: 6,
  },
  {
    title: "Управление портфелем проектов",
    skill: SKILL_NAMES.FREELANCE,
    description: "Портфель из десятков проектов",
    baseReward: 64000,
    reputation: 4,
    energyCost: 71,
    timeRequired: 12,
    requiredLevel: 6,
  },
  {
    title: "Стратегический консалтинг",
    skill: SKILL_NAMES.FREELANCE,
    description: "Консалтинг на уровне совета директоров",
    baseReward: 68000,
    reputation: 5,
    energyCost: 74,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Управление Enterprise проектом",
    skill: SKILL_NAMES.FREELANCE,
    description: "Крупнейший проект корпоративного уровня",
    baseReward: 72000,
    reputation: 5,
    energyCost: 76,
    timeRequired: 12,
    requiredLevel: 7,
  },
  {
    title: "Руководство цифровой трансформацией",
    skill: SKILL_NAMES.FREELANCE,
    description: "Трансформация крупной корпорации",
    baseReward: 75000,
    reputation: 5,
    energyCost: 78,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Переговоры на международном уровне",
    skill: SKILL_NAMES.FREELANCE,
    description: "Работа с глобальными клиентами",
    baseReward: 78000,
    reputation: 5,
    energyCost: 79,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Управление мега-проектом",
    skill: SKILL_NAMES.FREELANCE,
    description: "Координация проекта мирового масштаба",
    baseReward: 80000,
    reputation: 5,
    energyCost: 81,
    timeRequired: 13,
    requiredLevel: 7,
  },
  {
    title: "Стратегический директор проектов",
    skill: SKILL_NAMES.FREELANCE,
    description: "Руководство стратегическими инициативами",
    baseReward: 85000,
    reputation: 6,
    energyCost: 83,
    timeRequired: 14,
    requiredLevel: 8,
  },
  {
    title: "Управление глобальным проектом",
    skill: SKILL_NAMES.FREELANCE,
    description: "Международный проект мирового масштаба",
    baseReward: 90000,
    reputation: 6,
    energyCost: 85,
    timeRequired: 14,
    requiredLevel: 8,
  },
  {
    title: "Переговоры на уровне Fortune 500",
    skill: SKILL_NAMES.FREELANCE,
    description: "Работа с топ-500 компаниями мира",
    baseReward: 95000,
    reputation: 6,
    energyCost: 87,
    timeRequired: 15,
    requiredLevel: 8,
  },
  {
    title: "Руководство трансформацией холдинга",
    skill: SKILL_NAMES.FREELANCE,
    description: "Цифровая трансформация крупного холдинга",
    baseReward: 100000,
    reputation: 6,
    energyCost: 89,
    timeRequired: 15,
    requiredLevel: 8,
  },
  {
    title: "Управление портфелем Enterprise проектов",
    skill: SKILL_NAMES.FREELANCE,
    description: "Портфель корпоративных проектов",
    baseReward: 110000,
    reputation: 6,
    energyCost: 91,
    timeRequired: 16,
    requiredLevel: 8,
  },
  {
    title: "Стратегический консультант C-level",
    skill: SKILL_NAMES.FREELANCE,
    description: "Консалтинг для топ-менеджмента",
    baseReward: 120000,
    reputation: 7,
    energyCost: 94,
    timeRequired: 16,
    requiredLevel: 9,
  },
  {
    title: "Руководство глобальной трансформацией",
    skill: SKILL_NAMES.FREELANCE,
    description: "Международная цифровая трансформация",
    baseReward: 130000,
    reputation: 7,
    energyCost: 96,
    timeRequired: 17,
    requiredLevel: 9,
  },
  {
    title: "Управление проектом уровня CTO",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проект под руководством технического директора",
    baseReward: 140000,
    reputation: 7,
    energyCost: 98,
    timeRequired: 17,
    requiredLevel: 9,
  },
  {
    title: "Переговоры с международными гигантами",
    skill: SKILL_NAMES.FREELANCE,
    description: "Работа с крупнейшими корпорациями мира",
    baseReward: 150000,
    reputation: 7,
    energyCost: 100,
    timeRequired: 18,
    requiredLevel: 9,
  },
  {
    title: "Стратегический директор трансформаций",
    skill: SKILL_NAMES.FREELANCE,
    description: "Руководство трансформациями на глобальном уровне",
    baseReward: 160000,
    reputation: 7,
    energyCost: 102,
    timeRequired: 18,
    requiredLevel: 9,
  },
  {
    title: "Проект года в управлении",
    skill: SKILL_NAMES.FREELANCE,
    description: "Революционный проект управления премиум класса",
    baseReward: 170000,
    reputation: 7,
    energyCost: 104,
    timeRequired: 19,
    requiredLevel: 9,
  },
  {
    title: "Абсолютный пик управления проектами",
    skill: SKILL_NAMES.FREELANCE,
    description: "Вершина мастерства в управлении проектами",
    baseReward: 200000,
    reputation: 8,
    energyCost: 110,
    timeRequired: 20,
    requiredLevel: 10,
  },
  {
    title: "Легенда управления проектами",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проект, который войдет в историю управления",
    baseReward: 220000,
    reputation: 8,
    energyCost: 115,
    timeRequired: 20,
    requiredLevel: 10,
  },
  {
    title: "Управление проектом будущего",
    skill: SKILL_NAMES.FREELANCE,
    description: "Инновационное управление следующего поколения",
    baseReward: 240000,
    reputation: 8,
    energyCost: 120,
    timeRequired: 21,
    requiredLevel: 10,
  },
  {
    title: "Управление проектом ТОП-100",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проект для одной из крупнейших корпораций",
    baseReward: 260000,
    reputation: 8,
    energyCost: 125,
    timeRequired: 21,
    requiredLevel: 10,
  },
  {
    title: "Стратегический директор уровня CTO",
    skill: SKILL_NAMES.FREELANCE,
    description: "Руководство проектом для технического директора",
    baseReward: 300000,
    reputation: 8,
    energyCost: 130,
    timeRequired: 22,
    requiredLevel: 10,
  },
  {
    title: "Абсолютный шедевр управления",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проект, определяющий будущее управления проектами",
    baseReward: 350000,
    reputation: 9,
    energyCost: 140,
    timeRequired: 22,
    requiredLevel: 10,
  },
]

export const MARKETPLACE_ITEMS = {
  monitor: {
    name: "Игровой монитор",
    price: 5000,
    description: "Увеличивает получаемый опыт на 5 ед.",
    effect: { type: "xpBoost", value: 5 },
    category: "upgrade",
    requires: null,
  },
  monitorPro: {
    name: "Профессиональный монитор 4K",
    price: 15000,
    description: "Увеличивает получаемый опыт на 15 ед.",
    effect: { type: "xpBoost", value: 15 },
    category: "upgrade",
    requires: "monitor",
  },
  pc: {
    name: "Мощный ПК",
    price: 20000,
    description: "Снижает расход энергии на работу на 15%",
    effect: { type: "energyReduction", value: 0.15 },
    category: "upgrade",
    requires: null,
  },
  pcUltra: {
    name: "Топовая рабочая станция",
    price: 50000,
    description: "Снижает расход энергии на работу на 30%",
    effect: { type: "energyReduction", value: 0.3 },
    category: "upgrade",
    requires: "pc",
  },
  chair: {
    name: "Эргономичное кресло",
    price: 8000,
    description: "Увеличивает максимальную энергию на 20",
    effect: { type: "maxEnergy", value: 20 },
    category: "upgrade",
    requires: null,
  },
  chairPremium: {
    name: "Премиум кресло Herman Miller",
    price: 25000,
    description: "Увеличивает максимальную энергию на 50",
    effect: { type: "maxEnergy", value: 50 },
    category: "upgrade",
    requires: "chair",
  },
  keyboard: {
    name: "Механическая клавиатура",
    price: 3000,
    description: "Снижает время работы на 10 минут",
    effect: { type: "workSpeed", value: 10 },
    category: "upgrade",
    requires: null,
  },
  mouse: {
    name: "Игровая мышь",
    price: 4000,
    description: "Снижает время работы на 10 минут",
    effect: { type: "workSpeed", value: 10 },
    category: "upgrade",
    requires: null,
  },
  headphones: {
    name: "Наушники с шумоподавлением",
    price: 10000,
    description: "Увеличивает концентрацию: +10 ед. опыта",
    effect: { type: "xpBoost", value: 10 },
    category: "upgrade",
    requires: null,
  },
  desk: {
    name: "Регулируемый стол",
    price: 12000,
    description: "Улучшает здоровье: +5 к максимальному здоровью",
    effect: { type: "maxHealth", value: 5 },
    category: "upgrade",
    requires: null,
  },
  lamp: {
    name: "Настольная лампа",
    price: 2000,
    description: "Снижает усталость: +5% к максимальной энергии",
    effect: { type: "maxEnergy", value: 5 },
    category: "upgrade",
    requires: null,
  },
  webcam: {
    name: "Профессиональная веб-камера",
    price: 6000,
    description: "Для онлайн-встреч: +5% к репутации за заказы",
    effect: { type: "reputationBoost", value: 0.05 },
    category: "upgrade",
    requires: null,
  },
  microphone: {
    name: "Студийный микрофон",
    price: 8000,
    description: "Качественная связь: +3% к шансу взять заказ",
    effect: { type: "orderChance", value: 0.03 },
    category: "upgrade",
    requires: null,
  },
  secondMonitor: {
    name: "Второй монитор",
    price: 7000,
    description: "Многозадачность: -20 минут времени на работу",
    effect: { type: "workSpeed", value: 20 },
    category: "upgrade",
    requires: "monitor",
  },
  apartment: {
    name: "Переезд в квартиру в центре",
    price: 100000,
    description: "Аренда 20000₽/неделю, +15 ед. получаемого опыта",
    effect: { type: "betterApartment", value: 15 },
    category: "lifecycle",
    requires: null,
  },
  coworking: {
    name: "Абонемент в коворкинг",
    price: 15000,
    description: "Мотивация: +8 ед. получаемого опыта, но +2000₽/неделю",
    effect: { type: "coworking", value: 8 },
    category: "lifecycle",
    requires: null,
  },
  gym: {
    name: "Абонемент в спортзал",
    price: 5000,
    description: "Здоровье: +15 к максимальному здоровью",
    effect: { type: "maxHealth", value: 15 },
    category: "lifecycle",
    requires: null,
  },
  coffeeSubscription: {
    name: "Подписка на кофе",
    price: 3000,
    description: "Бесплатный кофе каждый день: +5 энергии утром",
    effect: { type: "dailyCoffee", value: 5 },
    category: "lifecycle",
    requires: null,
  },
}

export const BOOKS = {
  layoutBook: {
    name: "Верстай как профи",
    price: 3000,
    skill: SKILL_NAMES.LAYOUT,
    xp: 50,
    description: "Книга о современной верстке и адаптивном дизайне",
  },
  workpressBook: {
    name: "Workpress для профи",
    price: 3500,
    skill: SKILL_NAMES.WORKPRESS,
    xp: 50,
    description: "Полное руководство по разработке на Workpress",
  },
  freelanceBook: {
    name: "Фриланс без боли",
    price: 2500,
    skill: SKILL_NAMES.FREELANCE,
    xp: 50,
    description: "Как работать с клиентами и не сойти с ума",
  },
}

export const LEARNING_ACTIVITIES = {
  youtube: {
    label: "YouTube ролик",
    time: 1,
    xp: 8,
    energy: 5,
    description: "Быстрый способ узнать что-то новое",
  },
  google: {
    label: "Поиск в Google",
    time: 0.5,
    xp: 5,
    energy: 3,
    description: "Быстрый поиск ответа на вопрос",
  },
  freeCourse: {
    label: "Бесплатный курс",
    time: 3,
    xp: 20,
    energy: 15,
    description: "Структурированное обучение",
  },
  premiumCourse: {
    label: "Курс Арокена",
    time: 2,
    xp: 25,
    energy: 10,
    description: "Качественный материал от эксперта",
  },
  practice: {
    label: "Самостоятельная практика",
    time: 4,
    xp: 30,
    energy: 25,
    description: "Лучший способ закрепить знания",
  },
  documentation: {
    label: "Чтение документации",
    time: 2,
    xp: 15,
    energy: 8,
    description: "Изучение официальной документации",
  },
  tutorial: {
    label: "Интерактивный туториал",
    time: 1.5,
    xp: 12,
    energy: 7,
    description: "Практика с пошаговыми инструкциями",
  },
}

export const SLEEP_OPTIONS = [
  { hours: 4, energyRestore: 40, label: "4 часа (быстрый сон)" },
  { hours: 6, energyRestore: 70, label: "6 часов (короткий сон)" },
  { hours: 8, energyRestore: 100, label: "8 часов (полноценный сон)" },
  { hours: 10, energyRestore: 100, label: "10 часов (долгий сон)" },
]

export const FOOD_ITEMS = {
  doshik: {
    name: "Дошик",
    price: 150,
    satiety: 20,
    energy: 5,
    health: 0,
    category: "food",
    description: "Быстро, дешево, не очень полезно",
  },
  lunch: {
    name: "Обед",
    price: 400,
    satiety: 50,
    energy: 10,
    health: 0,
    category: "food",
    description: "Нормальная еда для нормального человека",
  },
  dinner: {
    name: "Ужин",
    price: 600,
    satiety: 70,
    energy: 15,
    health: 0,
    category: "food",
    description: "Плотный ужин восстанавливает силы",
  },
  vitamins: {
    name: "Витамины",
    price: 800,
    satiety: 0,
    energy: 0,
    health: 10,
    category: "health",
    description: "Восстанавливает немного здоровья",
  },
  firstAidKit: {
    name: "Аптечка",
    price: 3200,
    satiety: 0,
    energy: 0,
    health: 35,
    category: "health",
    description: "Восстанавливает здоровье",
  },
  coffee: {
    name: "Кофе",
    price: 200,
    satiety: 5,
    energy: 15,
    health: -2,
    category: "food",
    description: "Бодрит, но вредит здоровью",
  },
  energyDrink: {
    name: "Энергетик",
    price: 250,
    satiety: 0,
    energy: 25,
    health: -5,
    category: "food",
    description: "Сильный заряд энергии, но вредно",
  },
}

export const SIDE_JOBS = {
  courier: {
    name: "Курьер",
    time: 6,
    energy: 35,
    satiety: 10,
    health: 0,
    minPay: 1000,
    maxPay: 2000,
    description: "Развозить заказы по городу",
  },
  waiter: {
    name: "Официант",
    time: 7,
    energy: 40,
    satiety: 15,
    health: 0,
    minPay: 1500,
    maxPay: 2500,
    description: "Работа в кафе или ресторане",
  },
  loader: {
    name: "Грузчик",
    time: 8,
    energy: 50,
    satiety: 20,
    health: 5,
    minPay: 2000,
    maxPay: 3000,
    description: "Тяжелая физическая работа",
  },
  handyman: {
    name: "Разнорабочий",
    time: 6,
    energy: 30,
    satiety: 10,
    health: 0,
    minPay: 1000,
    maxPay: 1800,
    description: "Разная подсобная работа",
  },
}

export const BILLS = {
  rent: {
    name: "Квартира",
    amount: 10000,
    period: 7,
    description: "Оплата аренды квартиры",
  },
  internet: {
    name: "Интернет",
    amount: 1000,
    period: 7,
    description: "Оплата интернета",
  },
  coworking: {
    name: "Коворкинг",
    amount: 2000,
    period: 7,
    description: "Абонемент в коворкинг",
  },
}

export const SHOP_ITEMS = {
  bread: {
    name: "Хлеб",
    price: 80,
    satiety: 15,
    energy: 0,
    health: 0,
    description: "Базовый продукт для выживания",
  },
  water: {
    name: "Вода",
    price: 50,
    satiety: 5,
    energy: 0,
    health: 0,
    description: "Чистая питьевая вода",
  },
  cheapDoshik: {
    name: "Дешевый дошик",
    price: 100,
    satiety: 15,
    energy: 3,
    health: -1,
    description: "Самый дешевый вариант перекуса",
  },
  canned: {
    name: "Консервы",
    price: 200,
    satiety: 20,
    energy: 5,
    health: 0,
    description: "Тушенка или рыбные консервы",
  },
  snack: {
    name: "Снеки",
    price: 120,
    satiety: 10,
    energy: 8,
    health: -2,
    description: "Чипсы, сухарики - вредно, но быстро",
  },
  cheapCoffee: {
    name: "Растворимый кофе",
    price: 150,
    satiety: 0,
    energy: 10,
    health: -1,
    description: "Дешевый способ взбодриться",
  },
}
