import { SKILL_NAMES } from "./constants.js"

export const SKILL_INFO = {
  [SKILL_NAMES.LAYOUT]: {
    label: "Верстка",
  },
  [SKILL_NAMES.WORKPRESS]: {
    label: "Workpress",
  },
  [SKILL_NAMES.FREELANCE]: {
    label: "Фриланс",
  },
}

export const ORDER_TEMPLATES = [
  {
    title: "Простой лендинг",
    skill: SKILL_NAMES.LAYOUT,
    description: "Одностраничный сайт с базовой версткой",
    baseReward: 3000,
    reputation: 1,
    energyCost: 25,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Визитка для фотографа",
    skill: SKILL_NAMES.LAYOUT,
    description: "Минималистичный сайт-портфолио с галереей",
    baseReward: 4000,
    reputation: 1,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Лендинг по недвижимости",
    skill: SKILL_NAMES.LAYOUT,
    description: "Посадочная страница с адаптивом",
    baseReward: 12000,
    reputation: 1,
    energyCost: 35,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Корпоративный сайт",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт компании с формами",
    baseReward: 15000,
    reputation: 2,
    energyCost: 40,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Интерактивный лендинг",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сайт с параллакс-эффектами и анимациями",
    baseReward: 18000,
    reputation: 2,
    energyCost: 42,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сложный лендинг с анимациями",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт с анимациями",
    baseReward: 13000,
    reputation: 2,
    energyCost: 45,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Простой сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Базовая установка Workpress с готовой темой",
    baseReward: 5000,
    reputation: 1,
    energyCost: 30,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Блог на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настроить блог с категориями и комментариями",
    baseReward: 6000,
    reputation: 1,
    energyCost: 32,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Типовой сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Сверстать тему и натянуть на Workpress",
    baseReward: 14000,
    reputation: 2,
    energyCost: 45,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сайт с кастомными полями",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настроить ACF и создать удобные шаблоны",
    baseReward: 16000,
    reputation: 2,
    energyCost: 48,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Интернет-магазин Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Полноценный магазин с кастомными полями",
    baseReward: 20000,
    reputation: 3,
    energyCost: 60,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Консультация клиента",
    skill: SKILL_NAMES.FREELANCE,
    description: "Помочь определиться с требованиями к проекту",
    baseReward: 2000,
    reputation: 1,
    energyCost: 15,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Аудит сайта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проверить сайт на ошибки и дать рекомендации",
    baseReward: 3000,
    reputation: 1,
    energyCost: 20,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Правки для постоянного заказчика",
    skill: SKILL_NAMES.FREELANCE,
    description: "Исправить адаптив и настроить метрики",
    baseReward: 5000,
    reputation: 1,
    energyCost: 25,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Техническое задание",
    skill: SKILL_NAMES.FREELANCE,
    description: "Составить подробное ТЗ для разработчиков",
    baseReward: 8000,
    reputation: 2,
    energyCost: 30,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Ведение проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Полное сопровождение проекта от ТЗ до сдачи",
    baseReward: 25000,
    reputation: 3,
    energyCost: 50,
    timeRequired: 7,
    requiredLevel: 4,
  },
  {
    title: "Адаптивная верстка",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сверстать макет с адаптивом под все устройства",
    baseReward: 8000,
    reputation: 1,
    energyCost: 32,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Верстка email-рассылки",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сверстать письмо для email-маркетинга",
    baseReward: 4500,
    reputation: 1,
    energyCost: 25,
    timeRequired: 2,
    requiredLevel: 2,
  },
  {
    title: "Портфолио дизайнера",
    skill: SKILL_NAMES.LAYOUT,
    description: "Креативный сайт-портфолио с галереей работ",
    baseReward: 20000,
    reputation: 2,
    energyCost: 48,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Интернет-магазин",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный магазин с каталогом и корзиной",
    baseReward: 30000,
    reputation: 3,
    energyCost: 55,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Настройка плагинов Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Установить и настроить нужные плагины",
    baseReward: 7000,
    reputation: 1,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Оптимизация Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Ускорить загрузку сайта и настроить кеширование",
    baseReward: 10000,
    reputation: 2,
    energyCost: 38,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Миграция на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Перенести сайт с другой CMS на Workpress",
    baseReward: 18000,
    reputation: 2,
    energyCost: 52,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Кастомная тема Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Разработать уникальную тему с нуля",
    baseReward: 35000,
    reputation: 3,
    energyCost: 65,
    timeRequired: 9,
    requiredLevel: 5,
  },
  {
    title: "Переговоры с заказчиком",
    skill: SKILL_NAMES.FREELANCE,
    description: "Провести встречу и согласовать детали проекта",
    baseReward: 3500,
    reputation: 1,
    energyCost: 18,
    timeRequired: 2,
    requiredLevel: 2,
  },
  {
    title: "Презентация проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Подготовить и провести презентацию для клиента",
    baseReward: 6000,
    reputation: 2,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 3,
  },
  {
    title: "Управление командой",
    skill: SKILL_NAMES.FREELANCE,
    description: "Координировать работу дизайнера и разработчика",
    baseReward: 15000,
    reputation: 2,
    energyCost: 42,
    timeRequired: 5,
    requiredLevel: 4,
  },
  {
    title: "Крупный проект под ключ",
    skill: SKILL_NAMES.FREELANCE,
    description: "Полный цикл разработки корпоративного сайта",
    baseReward: 40000,
    reputation: 4,
    energyCost: 60,
    timeRequired: 10,
    requiredLevel: 5,
  },
]

export const MARKETPLACE_ITEMS = {
  monitor: {
    name: "Игровой монитор",
    price: 5000,
    description: "Увеличивает получаемый опыт на 5 ед.",
    effect: { type: "xpBoost", value: 5 },
    category: "upgrade",
    requires: null,
  },
  monitorPro: {
    name: "Профессиональный монитор 4K",
    price: 15000,
    description: "Увеличивает получаемый опыт на 15 ед.",
    effect: { type: "xpBoost", value: 15 },
    category: "upgrade",
    requires: "monitor",
  },
  pc: {
    name: "Мощный ПК",
    price: 20000,
    description: "Снижает расход энергии на работу на 15%",
    effect: { type: "energyReduction", value: 0.15 },
    category: "upgrade",
    requires: null,
  },
  pcUltra: {
    name: "Топовая рабочая станция",
    price: 50000,
    description: "Снижает расход энергии на работу на 30%",
    effect: { type: "energyReduction", value: 0.3 },
    category: "upgrade",
    requires: "pc",
  },
  chair: {
    name: "Эргономичное кресло",
    price: 8000,
    description: "Увеличивает максимальную энергию на 20",
    effect: { type: "maxEnergy", value: 20 },
    category: "upgrade",
    requires: null,
  },
  chairPremium: {
    name: "Премиум кресло Herman Miller",
    price: 25000,
    description: "Увеличивает максимальную энергию на 50",
    effect: { type: "maxEnergy", value: 50 },
    category: "upgrade",
    requires: "chair",
  },
  keyboard: {
    name: "Механическая клавиатура",
    price: 3000,
    description: "Снижает время работы на 10 минут",
    effect: { type: "workSpeed", value: 10 },
    category: "upgrade",
    requires: null,
  },
  mouse: {
    name: "Игровая мышь",
    price: 4000,
    description: "Снижает время работы на 10 минут",
    effect: { type: "workSpeed", value: 10 },
    category: "upgrade",
    requires: null,
  },
  headphones: {
    name: "Наушники с шумоподавлением",
    price: 10000,
    description: "Увеличивает концентрацию: +10 ед. опыта",
    effect: { type: "xpBoost", value: 10 },
    category: "upgrade",
    requires: null,
  },
  desk: {
    name: "Регулируемый стол",
    price: 12000,
    description: "Улучшает здоровье: +5 к максимальному здоровью",
    effect: { type: "maxHealth", value: 5 },
    category: "upgrade",
    requires: null,
  },
  lamp: {
    name: "Настольная лампа",
    price: 2000,
    description: "Снижает усталость: +5% к максимальной энергии",
    effect: { type: "maxEnergy", value: 5 },
    category: "upgrade",
    requires: null,
  },
  webcam: {
    name: "Профессиональная веб-камера",
    price: 6000,
    description: "Для онлайн-встреч: +5% к репутации за заказы",
    effect: { type: "reputationBoost", value: 0.05 },
    category: "upgrade",
    requires: null,
  },
  microphone: {
    name: "Студийный микрофон",
    price: 8000,
    description: "Качественная связь: +3% к шансу взять заказ",
    effect: { type: "orderChance", value: 0.03 },
    category: "upgrade",
    requires: null,
  },
  secondMonitor: {
    name: "Второй монитор",
    price: 7000,
    description: "Многозадачность: -20 минут времени на работу",
    effect: { type: "workSpeed", value: 20 },
    category: "upgrade",
    requires: "monitor",
  },
  apartment: {
    name: "Переезд в квартиру в центре",
    price: 100000,
    description: "Аренда 20000₽/неделю, +15 ед. получаемого опыта",
    effect: { type: "betterApartment", value: 15 },
    category: "lifecycle",
    requires: null,
  },
  coworking: {
    name: "Абонемент в коворкинг",
    price: 15000,
    description: "Мотивация: +8 ед. получаемого опыта, но +2000₽/неделю",
    effect: { type: "coworking", value: 8 },
    category: "lifecycle",
    requires: null,
  },
  gym: {
    name: "Абонемент в спортзал",
    price: 5000,
    description: "Здоровье: +15 к максимальному здоровью",
    effect: { type: "maxHealth", value: 15 },
    category: "lifecycle",
    requires: null,
  },
  coffeeSubscription: {
    name: "Подписка на кофе",
    price: 3000,
    description: "Бесплатный кофе каждый день: +5 энергии утром",
    effect: { type: "dailyCoffee", value: 5 },
    category: "lifecycle",
    requires: null,
  },
}

export const BOOKS = {
  layoutBook: {
    name: "Верстай как профи",
    price: 3000,
    skill: SKILL_NAMES.LAYOUT,
    xp: 50,
    description: "Книга о современной верстке и адаптивном дизайне",
  },
  workpressBook: {
    name: "Workpress для профи",
    price: 3500,
    skill: SKILL_NAMES.WORKPRESS,
    xp: 50,
    description: "Полное руководство по разработке на Workpress",
  },
  freelanceBook: {
    name: "Фриланс без боли",
    price: 2500,
    skill: SKILL_NAMES.FREELANCE,
    xp: 50,
    description: "Как работать с клиентами и не сойти с ума",
  },
}

export const LEARNING_ACTIVITIES = {
  youtube: {
    label: "YouTube ролик",
    time: 1,
    xp: 8,
    energy: 5,
    description: "Быстрый способ узнать что-то новое",
  },
  google: {
    label: "Поиск в Google",
    time: 0.5,
    xp: 5,
    energy: 3,
    description: "Быстрый поиск ответа на вопрос",
  },
  freeCourse: {
    label: "Бесплатный курс",
    time: 3,
    xp: 20,
    energy: 15,
    description: "Структурированное обучение",
  },
  premiumCourse: {
    label: "Курс Арокена",
    time: 2,
    xp: 25,
    energy: 10,
    description: "Качественный материал от эксперта",
  },
  practice: {
    label: "Самостоятельная практика",
    time: 4,
    xp: 30,
    energy: 25,
    description: "Лучший способ закрепить знания",
  },
  documentation: {
    label: "Чтение документации",
    time: 2,
    xp: 15,
    energy: 8,
    description: "Изучение официальной документации",
  },
  tutorial: {
    label: "Интерактивный туториал",
    time: 1.5,
    xp: 12,
    energy: 7,
    description: "Практика с пошаговыми инструкциями",
  },
}

export const SLEEP_OPTIONS = [
  { hours: 4, energyRestore: 40, label: "4 часа (быстрый сон)" },
  { hours: 6, energyRestore: 70, label: "6 часов (короткий сон)" },
  { hours: 8, energyRestore: 100, label: "8 часов (полноценный сон)" },
  { hours: 10, energyRestore: 100, label: "10 часов (долгий сон)" },
]

export const FOOD_ITEMS = {
  doshik: {
    name: "Дошик",
    price: 150,
    satiety: 20,
    energy: 5,
    health: 0,
    category: "food",
    description: "Быстро, дешево, не очень полезно",
  },
  lunch: {
    name: "Обед",
    price: 400,
    satiety: 50,
    energy: 10,
    health: 0,
    category: "food",
    description: "Нормальная еда для нормального человека",
  },
  dinner: {
    name: "Ужин",
    price: 600,
    satiety: 70,
    energy: 15,
    health: 0,
    category: "food",
    description: "Плотный ужин восстанавливает силы",
  },
  vitamins: {
    name: "Витамины",
    price: 800,
    satiety: 0,
    energy: 0,
    health: 10,
    category: "health",
    description: "Восстанавливает немного здоровья",
  },
  firstAidKit: {
    name: "Аптечка",
    price: 3200,
    satiety: 0,
    energy: 0,
    health: 35,
    category: "health",
    description: "Восстанавливает здоровье",
  },
  coffee: {
    name: "Кофе",
    price: 200,
    satiety: 5,
    energy: 15,
    health: -2,
    category: "food",
    description: "Бодрит, но вредит здоровью",
  },
  energyDrink: {
    name: "Энергетик",
    price: 250,
    satiety: 0,
    energy: 25,
    health: -5,
    category: "food",
    description: "Сильный заряд энергии, но вредно",
  },
}

export const SIDE_JOBS = {
  courier: {
    name: "Курьер",
    time: 6,
    energy: 35,
    satiety: 10,
    health: 0,
    minPay: 1000,
    maxPay: 2000,
    description: "Развозить заказы по городу",
  },
  waiter: {
    name: "Официант",
    time: 7,
    energy: 40,
    satiety: 15,
    health: 0,
    minPay: 1500,
    maxPay: 2500,
    description: "Работа в кафе или ресторане",
  },
  loader: {
    name: "Грузчик",
    time: 8,
    energy: 50,
    satiety: 20,
    health: 5,
    minPay: 2000,
    maxPay: 3000,
    description: "Тяжелая физическая работа",
  },
  handyman: {
    name: "Разнорабочий",
    time: 6,
    energy: 30,
    satiety: 10,
    health: 0,
    minPay: 1000,
    maxPay: 1800,
    description: "Разная подсобная работа",
  },
}

export const BILLS = {
  rent: {
    name: "Квартира",
    amount: 10000,
    period: 7,
    description: "Оплата аренды квартиры",
  },
  internet: {
    name: "Интернет",
    amount: 1000,
    period: 7,
    description: "Оплата интернета",
  },
  coworking: {
    name: "Коворкинг",
    amount: 2000,
    period: 7,
    description: "Абонемент в коворкинг",
  },
}

export const SHOP_ITEMS = {
  bread: {
    name: "Хлеб",
    price: 80,
    satiety: 15,
    energy: 0,
    health: 0,
    description: "Базовый продукт для выживания",
  },
  water: {
    name: "Вода",
    price: 50,
    satiety: 5,
    energy: 0,
    health: 0,
    description: "Чистая питьевая вода",
  },
  cheapDoshik: {
    name: "Дешевый дошик",
    price: 100,
    satiety: 15,
    energy: 3,
    health: -1,
    description: "Самый дешевый вариант перекуса",
  },
  canned: {
    name: "Консервы",
    price: 200,
    satiety: 20,
    energy: 5,
    health: 0,
    description: "Тушенка или рыбные консервы",
  },
  snack: {
    name: "Снеки",
    price: 120,
    satiety: 10,
    energy: 8,
    health: -2,
    description: "Чипсы, сухарики - вредно, но быстро",
  },
  cheapCoffee: {
    name: "Растворимый кофе",
    price: 150,
    satiety: 0,
    energy: 10,
    health: -1,
    description: "Дешевый способ взбодриться",
  },
}
