import { SKILL_NAMES } from "./constants.js"

export const SKILL_INFO = {
  [SKILL_NAMES.LAYOUT]: {
    label: "Верстка",
  },
  [SKILL_NAMES.WORKPRESS]: {
    label: "Workpress",
  },
  [SKILL_NAMES.FREELANCE]: {
    label: "Фриланс",
  },
}

export const ORDER_TEMPLATES = [
  {
    title: "Простой лендинг",
    skill: SKILL_NAMES.LAYOUT,
    description: "Одностраничный сайт с базовой версткой",
    baseReward: 3000,
    reputation: 1,
    energyCost: 25,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Визитка для фотографа",
    skill: SKILL_NAMES.LAYOUT,
    description: "Минималистичный сайт-портфолио с галереей",
    baseReward: 4000,
    reputation: 1,
    energyCost: 28,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Лендинг по недвижимости",
    skill: SKILL_NAMES.LAYOUT,
    description: "Посадочная страница с адаптивом",
    baseReward: 12000,
    reputation: 1,
    energyCost: 35,
    timeRequired: 4,
    requiredLevel: 2,
  },
  {
    title: "Корпоративный сайт",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт компании с формами",
    baseReward: 15000,
    reputation: 2,
    energyCost: 40,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Интерактивный лендинг",
    skill: SKILL_NAMES.LAYOUT,
    description: "Сайт с параллакс-эффектами и анимациями",
    baseReward: 18000,
    reputation: 2,
    energyCost: 42,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сложный лендинг с анимациями",
    skill: SKILL_NAMES.LAYOUT,
    description: "Многостраничный сайт с анимациями",
    baseReward: 13000,
    reputation: 2,
    energyCost: 45,
    timeRequired: 6,
    requiredLevel: 4,
  },
  {
    title: "Простой сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Базовая установка Workpress с готовой темой",
    baseReward: 5000,
    reputation: 1,
    energyCost: 30,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Блог на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настроить блог с категориями и комментариями",
    baseReward: 6000,
    reputation: 1,
    energyCost: 32,
    timeRequired: 3,
    requiredLevel: 1,
  },
  {
    title: "Типовой сайт на Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Сверстать тему и натянуть на Workpress",
    baseReward: 14000,
    reputation: 2,
    energyCost: 45,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Сайт с кастомными полями",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Настроить ACF и создать удобные шаблоны",
    baseReward: 16000,
    reputation: 2,
    energyCost: 48,
    timeRequired: 5,
    requiredLevel: 3,
  },
  {
    title: "Интернет-магазин Workpress",
    skill: SKILL_NAMES.WORKPRESS,
    description: "Полноценный магазин с кастомными полями",
    baseReward: 20000,
    reputation: 3,
    energyCost: 60,
    timeRequired: 8,
    requiredLevel: 5,
  },
  {
    title: "Консультация клиента",
    skill: SKILL_NAMES.FREELANCE,
    description: "Помочь определиться с требованиями к проекту",
    baseReward: 2000,
    reputation: 1,
    energyCost: 15,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Аудит сайта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Проверить сайт на ошибки и дать рекомендации",
    baseReward: 3000,
    reputation: 1,
    energyCost: 20,
    timeRequired: 2,
    requiredLevel: 1,
  },
  {
    title: "Правки для постоянного заказчика",
    skill: SKILL_NAMES.FREELANCE,
    description: "Исправить адаптив и настроить метрики",
    baseReward: 5000,
    reputation: 1,
    energyCost: 25,
    timeRequired: 3,
    requiredLevel: 2,
  },
  {
    title: "Техническое задание",
    skill: SKILL_NAMES.FREELANCE,
    description: "Составить подробное ТЗ для разработчиков",
    baseReward: 8000,
    reputation: 2,
    energyCost: 30,
    timeRequired: 4,
    requiredLevel: 3,
  },
  {
    title: "Ведение проекта",
    skill: SKILL_NAMES.FREELANCE,
    description: "Полное сопровождение проекта от ТЗ до сдачи",
    baseReward: 25000,
    reputation: 3,
    energyCost: 50,
    timeRequired: 7,
    requiredLevel: 4,
  },
]

export const ORDERS = [
  {
    id: 1,
    title: "Лендинг для кафе",
    description: "Простая одностраничка с меню и контактами",
    reward: 3000,
    timeRequired: 4,
    energyCost: 40,
    skill: SKILL_NAMES.LAYOUT,
    requiredLevel: 1,
    deadline: 3,
  },
  {
    id: 2,
    title: "Сайт на Workpress",
    description: "Блог с готовой темой и настройками",
    reward: 5000,
    timeRequired: 6,
    energyCost: 55,
    skill: SKILL_NAMES.WORKPRESS,
    requiredLevel: 1,
    deadline: 4,
  },
  {
    id: 3,
    title: "Консультация клиента",
    description: "Помочь определиться с требованиями к проекту",
    reward: 2000,
    timeRequired: 3,
    energyCost: 30,
    skill: SKILL_NAMES.FREELANCE,
    requiredLevel: 1,
    deadline: 2,
  },
  {
    id: 4,
    title: "Корпоративный сайт",
    description: "Многостраничный сайт компании с формами",
    reward: 15000,
    timeRequired: 8,
    energyCost: 60,
    skill: SKILL_NAMES.LAYOUT,
    requiredLevel: 3,
    deadline: 5,
  },
  {
    id: 5,
    title: "Интернет-магазин на Workpress",
    description: "Полноценный магазин с кастомными полями",
    reward: 20000,
    timeRequired: 10,
    energyCost: 70,
    skill: SKILL_NAMES.WORKPRESS,
    requiredLevel: 4,
    deadline: 7,
  },
  {
    id: 6,
    title: "Ведение проекта",
    description: "Полное сопровождение проекта от ТЗ до сдачи",
    reward: 25000,
    timeRequired: 12,
    energyCost: 80,
    skill: SKILL_NAMES.FREELANCE,
    requiredLevel: 4,
    deadline: 10,
  },
]

export const MARKETPLACE_ITEMS = {
  monitor: {
    name: "Игровой монитор",
    price: 5000,
    description: "Увеличивает получаемый опыт на 5 ед.",
    effect: { type: "xpBoost", value: 5 },
    category: "upgrade",
    requires: null,
  },
  pc: {
    name: "Мощный ПК",
    price: 20000,
    description: "Снижает расход энергии на работу на 15%",
    effect: { type: "energyReduction", value: 0.15 },
    category: "upgrade",
    requires: null,
  },
  chair: {
    name: "Эргономичное кресло",
    price: 8000,
    description: "Увеличивает максимальную энергию на 20",
    effect: { type: "maxEnergy", value: 20 },
    category: "upgrade",
    requires: null,
  },
}

export const BOOKS = {
  layoutBook: {
    name: "Верстай как профи",
    price: 3000,
    skill: SKILL_NAMES.LAYOUT,
    xp: 50,
    description: "Книга о современной верстке и адаптивном дизайне",
  },
  workpressBook: {
    name: "Workpress для профи",
    price: 3500,
    skill: SKILL_NAMES.WORKPRESS,
    xp: 50,
    description: "Полное руководство по разработке на Workpress",
  },
  freelanceBook: {
    name: "Фриланс без боли",
    price: 2500,
    skill: SKILL_NAMES.FREELANCE,
    xp: 50,
    description: "Как работать с клиентами и не сойти с ума",
  },
}

export const LEARNING_ACTIVITIES = {
  youtube: {
    label: "YouTube ролик",
    time: 1,
    xp: 8,
    energy: 5,
    description: "Быстрый способ узнать что-то новое",
  },
  google: {
    label: "Поиск в Google",
    time: 0.5,
    xp: 5,
    energy: 3,
    description: "Быстрый поиск ответа на вопрос",
  },
  freeCourse: {
    label: "Бесплатный курс",
    time: 3,
    xp: 20,
    energy: 15,
    description: "Структурированное обучение",
  },
  premiumCourse: {
    label: "Курс Арокена",
    time: 2,
    xp: 25,
    energy: 10,
    description: "Качественный материал от эксперта",
  },
  practice: {
    label: "Самостоятельная практика",
    time: 4,
    xp: 30,
    energy: 25,
    description: "Лучший способ закрепить знания",
  },
  documentation: {
    label: "Чтение документации",
    time: 2,
    xp: 15,
    energy: 8,
    description: "Изучение официальной документации",
  },
  tutorial: {
    label: "Интерактивный туториал",
    time: 1.5,
    xp: 12,
    energy: 7,
    description: "Практика с пошаговыми инструкциями",
  },
}

export const SLEEP_OPTIONS = [
  { hours: 4, energyRestore: 40, label: "4 часа (быстрый сон)" },
  { hours: 6, energyRestore: 70, label: "6 часов (короткий сон)" },
  { hours: 8, energyRestore: 100, label: "8 часов (полноценный сон)" },
  { hours: 10, energyRestore: 100, label: "10 часов (долгий сон)" },
]

export const FOOD_ITEMS = {
  doshik: {
    name: "Дошик",
    price: 150,
    satiety: 20,
    energy: 5,
    health: 0,
    category: "food",
    description: "Быстро, дешево, не очень полезно",
  },
  lunch: {
    name: "Обед",
    price: 400,
    satiety: 50,
    energy: 10,
    health: 0,
    category: "food",
    description: "Нормальная еда для нормального человека",
  },
  dinner: {
    name: "Ужин",
    price: 600,
    satiety: 70,
    energy: 15,
    health: 0,
    category: "food",
    description: "Плотный ужин восстанавливает силы",
  },
  vitamins: {
    name: "Витамины",
    price: 800,
    satiety: 0,
    energy: 0,
    health: 10,
    category: "health",
    description: "Восстанавливает немного здоровья",
  },
  firstAidKit: {
    name: "Аптечка",
    price: 3200,
    satiety: 0,
    energy: 0,
    health: 35,
    category: "health",
    description: "Восстанавливает здоровье",
  },
}
