export const STORAGE_KEY = "freelancer-sim-state-v1"

export const GAME_CONSTANTS = {
  INITIAL_DAY: 1,
  INITIAL_TIME: 9,
  DELIVERY_TIME: 9,
  INITIAL_MONEY: 5000,
  INITIAL_ENERGY: 100,
  MAX_ENERGY: 100,
  INITIAL_HEALTH: 100,
  INITIAL_SATIETY: 100,
  HOURS_IN_DAY: 24,
  MINUTES_IN_HOUR: 60,
  WORK_PROGRESS_STEP: 25,
  PROGRESS_COMPLETE: 100,
  INITIAL_SKILL_LEVEL: 0,
  INITIAL_SKILL_XP: 0,
  XP_FOR_FIRST_LEVEL: 150,
  XP_PER_LEVEL_MULTIPLIER: 100,
  XP_GAIN_DIVIDER: 500,
  SATIETY_DECREASE_INTERVAL: 3,
  SATIETY_DECREASE_AMOUNT: 10,
  HEALTH_PENALTY_ON_STARVATION: 10,
  LOW_SATIETY_THRESHOLD: 30,
  LOW_ENERGY_THRESHOLD: 20,
  LOW_HEALTH_THRESHOLD: 30,
  LATE_SLEEP_PENALTY: 0.7,
  LATE_SLEEP_START_HOUR: 24,
  LATE_SLEEP_END_HOUR: 6,
  ENERGY_PENALTY_PER_LEVEL_DIFF: 0.5,
  DEFAULT_ORDER_DEADLINE: 3,
  PENALTY_PER_OVERDUE_DAY: 0.2,
  HOSPITAL_MONEY_PENALTY: 0.3,
  HOSPITAL_TIME_PENALTY_DAYS: 1,
  HOSPITAL_HEALTH_RESTORE: 0.5,
  HOSPITAL_SKILL_PENALTY: 0.9,
  HOSPITAL_SATIETY_RESTORE: 70,
  HOSPITAL_MORNING_HOUR: 8,
}

export const UI_SELECTORS = {
  STAT_DAY: "stat-day",
  STAT_TIME: "stat-time",
  STAT_ENERGY: "stat-energy",
  STAT_HEALTH: "stat-health",
  STAT_SATIETY: "stat-satiety",
  STAT_MONEY: "stat-money",
  STAT_REP: "stat-rep",
  PORTFOLIO_WINDOW: "portfolio-window",
  WZCODE_WINDOW: "wzcode-window",
  BROWSER_WINDOW: "browser-window",
  SKILLS_WINDOW: "skills-window",
  LEARNING_WINDOW: "learning-window",
  TELEHLAM_WINDOW: "telehlam-window",
  SLEEP_WINDOW: "sleep-window",
  CHARACTER_WINDOW: "character-window",
  WZCODE_BODY: "wzcode-body",
  BROWSER_BODY: "browser-body",
  SKILLS_BODY: "skills-body",
  LEARNING_BODY: "learning-body",
  TELEHLAM_BODY: "telehlam-body",
  SLEEP_BODY: "sleep-body",
  PORTFOLIO_BODY: "portfolio-body",
  CHARACTER_BODY: "character-body",
}

export const MESSAGES = {
  NO_ENERGY: "Недостаточно энергии!",
  ORDER_COMPLETED: "Заказ выполнен!",
  ORDER_TAKEN: "принят! Открой WZ Code для работы.",
  ACTIVE_ORDER_EXISTS: "У вас уже есть активный заказ!",
  NO_ORDERS: "Все заказы разобраны. Приходи позже!",
  NO_ACTIVE_ORDER: "Нет активных заказов.",
  CHECK_KRORK: "Загляни в браузер на биржу Krork!",
  APP_IN_DEVELOPMENT: "Приложение в разработке",
  LEVEL_UP: "Уровень повышен!",
}

export const SKILL_NAMES = {
  LAYOUT: "layout",
  WORKPRESS: "workpress",
  FREELANCE: "freelance",
}

export const SKILL_LABELS = {
  [SKILL_NAMES.LAYOUT]: "Верстка",
  [SKILL_NAMES.WORKPRESS]: "Workpress",
  [SKILL_NAMES.FREELANCE]: "Фриланс",
}
