export const STORAGE_KEY = "freelancer-sim-state-v1"

export const GAME_CONSTANTS = {
  INITIAL_DAY: 1,
  INITIAL_TIME: 9,
  DELIVERY_TIME: 9,
  INITIAL_MONEY: 3000,
  INITIAL_ENERGY: 100,
  MAX_ENERGY: 100,
  INITIAL_HEALTH: 100,
  INITIAL_SATIETY: 100,
  INITIAL_REPUTATION: 0,
  HOURS_IN_DAY: 24,
  MINUTES_IN_HOUR: 60,
  WORK_PROGRESS_STEP: 25,
  PROGRESS_COMPLETE: 100,
  INITIAL_SKILL_LEVEL: 0,
  INITIAL_SKILL_XP: 0,
  XP_FOR_FIRST_LEVEL: 200,
  XP_PER_LEVEL_INCREMENT: 100,
  MAX_SKILL_LEVEL: 10,
  XP_GAIN_DIVIDER: 500,
  SATIETY_DECREASE_INTERVAL: 3,
  SATIETY_DECREASE_AMOUNT: 10,
  HEALTH_PENALTY_ON_STARVATION: 10,
  LOW_SATIETY_THRESHOLD: 30,
  LOW_ENERGY_THRESHOLD: 20,
  LOW_HEALTH_THRESHOLD: 30,
  LATE_SLEEP_PENALTY: 0.7,
  LATE_SLEEP_START_HOUR: 24,
  LATE_SLEEP_END_HOUR: 6,
  ENERGY_PENALTY_PER_LEVEL_DIFF: 0.5,
  DEFAULT_ORDER_DEADLINE: 3,
  PENALTY_PER_OVERDUE_DAY: 0.2,
  HOSPITAL_MONEY_PENALTY: 0.3,
  HOSPITAL_TIME_PENALTY_DAYS: 3,
  HOSPITAL_HEALTH_RESTORE: 0.5,
  HOSPITAL_SKILL_PENALTY: 0.9,
  HOSPITAL_SATIETY_RESTORE: 70,
  HOSPITAL_MORNING_HOUR: 8,
  NIGHT_START_HOUR: 23,
  NIGHT_END_HOUR: 6,
  NIGHT_HEALTH_PENALTY_PER_HOUR: 3,
  MIN_ORDERS_COUNT: 2,
  MAX_ORDERS_COUNT: 6,
  ORDER_LEVEL_RANGE: 2,
  POSITIVE_EVENT_CHANCE: 0.15,
  NEGATIVE_EVENT_CHANCE: 0.05,
  DUAL_EVENT_CHANCE: 0.1,
  CREATIVE_CRISIS_EVENING_HOUR: 17,
  XP_BONUS_MONITOR_PRO: 15,
  XP_BONUS_MONITOR: 5,
  XP_BONUS_HEADPHONES: 10,
  XP_BONUS_APARTMENT: 15,
  XP_BONUS_COWORKING: 8,
  TELEHLAM_BASE_XP: 15,
  ORDER_CHANCE_MAX_BASE: 75,
  ORDER_CHANCE_PER_LEVEL: 15,
  ORDER_CHANCE_MAX_REPUTATION_BONUS: 50,
  ORDER_CHANCE_REPUTATION_MULTIPLIER: 0.5,
  ORDER_CHANCE_MICROPHONE_BONUS: 3,
  ORDER_CHANCE_MAX_TOTAL: 100,
  ORDER_REWARD_REPUTATION_MULTIPLIER: 0.01,
  STAT_COLOR_HIGH_THRESHOLD: 50,
  STAT_COLOR_MEDIUM_THRESHOLD: 20,
  TIME_FORMAT_MIN_DIGITS: 2,
  ICON_SIZE_PX: 16,
  ICON_TEXT_GAP_PX: 10,
  JOBS_UNLOCK_MIN_SKILL_LEVEL: 3,
  JOBS_REQUIRED_SKILL_LEVEL: 10,
  JOBS_REQUIRED_REPUTATION: 50,
  ENDING_VIDEO_PATH: "video/end.mp4",
  ENDING_DIALOGS: [
    "Когда я только начал учиться на Арокен.ру, я был уверен, что веб-разработка — это когда делаешь кнопку, и она просто… работает.",
    "Ха. Ха. Ха.",
    "Оказалось, что самое сложное — заставить кнопку не уезжать на 200 пикселей вниз без моего разрешения.",
    "И если бы не курс Арокен.ру, кураторы и наше сообщество, я бы до сих пор искал, где закрывается тег <div>.",
    "Вы не просто дали мне знания — вы дали мне ощущение, что я действительно могу.",
    "Спасибо вам за помощь, за энергию, за то, что отвечали на вопросы, которые я стеснялся даже формулировать.",
    "И за то, что иногда объясняли так просто, как будто я программирую тостер.",
    "Эта игра — результат всех тех вечеров, когда я сидел над кодом, ругался, гуглил, снова ругался — и всё равно продолжал.",
    "А сейчас... ну, пусть тут всё ещё есть баги, зато они — мои.",
    "Спасибо вам за то, что вы есть.",
    "И за то, что однажды научили меня тому, что всё возможно — даже если это твоя первая игра.",
  ],
}

export const UI_SELECTORS = {
  STAT_DAY: "stat-day",
  STAT_TIME: "stat-time",
  STAT_ENERGY: "stat-energy",
  STAT_HEALTH: "stat-health",
  STAT_SATIETY: "stat-satiety",
  STAT_MONEY: "stat-money",
  STAT_REP: "stat-rep",
  PORTFOLIO_WINDOW: "portfolio-window",
  WZCODE_WINDOW: "wzcode-window",
  BROWSER_WINDOW: "browser-window",
  SKILLS_WINDOW: "skills-window",
  LEARNING_WINDOW: "learning-window",
  TELEHLAM_WINDOW: "telehlam-window",
  SLEEP_WINDOW: "sleep-window",
  CHARACTER_WINDOW: "character-window",
  JOBS_WINDOW: "jobs-window",
  WZCODE_BODY: "wzcode-body",
  BROWSER_BODY: "browser-body",
  SKILLS_BODY: "skills-body",
  LEARNING_BODY: "learning-body",
  TELEHLAM_BODY: "telehlam-body",
  SLEEP_BODY: "sleep-body",
  PORTFOLIO_BODY: "portfolio-body",
  CHARACTER_BODY: "character-body",
  JOBS_BODY: "jobs-body",
}

export const MESSAGES = {
  NO_ENERGY: "Недостаточно энергии!",
  ORDER_COMPLETED: "Заказ выполнен!",
  ORDER_TAKEN: "принят! Открой WZ Code для работы.",
  ACTIVE_ORDER_EXISTS: "У вас уже есть активный заказ!",
  NO_ORDERS: "Все заказы разобраны. Приходи позже!",
  NO_ACTIVE_ORDER: "Нет активных заказов.",
  CHECK_KRORK: "Загляни в браузер на биржу Krork!",
  APP_IN_DEVELOPMENT: "Приложение в разработке",
  LEVEL_UP: "Уровень повышен!",
}

export const SKILL_NAMES = {
  LAYOUT: "layout",
  WORKPRESS: "workpress",
  FREELANCE: "freelance",
}

export const SKILL_LABELS = {
  [SKILL_NAMES.LAYOUT]: "Верстка",
  [SKILL_NAMES.WORKPRESS]: "Workpress",
  [SKILL_NAMES.FREELANCE]: "Фриланс",
}

export const AVAILABLE_APPS = [
  "portfolio",
  "wzcode",
  "browser",
  "skills",
  "learning",
  "sleep",
  "telehlam",
  "character",
  "sidejob",
  "bills",
  "shop",
  "settings",
  "jobs",
]
